name: Perform golang unit tests
on:
    push:
      branches: 
        - main
    pull_request:
      branches:
        - main
jobs:
    build:
      runs-on: ubuntu-latest
      env:
        MYSQL_TEST_DB_URI: admin:admin@tcp(localhost:3307)/fake_data_generator_app?charset=utf8mb4&parseTime=True&loc=Local

        GIN_MODE: GITHUB_ACTIONS
        MYSQL_USER: admin
        MONGO_DB_NAME: fake_data_generator_app
        MONGO_ENDPOINT_COLLECTION: endpoints
        MONGO_TEST_DB_URI: mongodb://admin:admin@localhost:27018
      services:
        # add docker mysql service running on port 3307
        mysql:
          image: mysql:latest
          ports:
            - 3307:3306
          env:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: fake_data_generator_app
        # add docker mongo service running on port 27018
        mongo:
          image: mongo:latest
          ports:
            - 27018:27017
          env:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
      steps:
        - uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
        - name: Build
          run: go build -v ./...
        - name: Test
          run: go test -v ./...